name: VaultR UI [PROD]

on:
  push:
    branches: [ "main" ]

jobs:

  status:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Building and pushing VaultR UI image to Docker Hub."

      - name: Print location
        run: ls -R

  build-and-push:

    runs-on: ubuntu-latest
    environment: production

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: wmanka/vaultr-ui:latest
